export const STREAMING_API_BASE_URL = process.env.REACT_APP_STREAMING_API_BASE_URL;
export const STREAMING_API_HOST = process.env.REACT_APP_STREAMING_API_HOST;
export const STREAMING_API_KEY = process.env.REACT_APP_STREAMING_API_KEY;
